name: FLLMS02
channels:
  - conda-forge
dependencies:
  - python=3.11
  - numpy
  - pandas
  - matplotlib
  - scikit-learn
  - jupyterlab
  - notebook
  - ipykernel
  - pip
  - pip:
      - tensorflow
