name: aula01-intro-ml
channels:
  - conda-forge
  - nodefaults
dependencies:
  - python=3.11
  - pip
  - jupyterlab
  - ipykernel
  - numpy
  - pandas
  - matplotlib
  - seaborn
  - scikit-learn
  - nltk
  - pip:
      - transformers
      - https://download.pytorch.org/whl/cpu/torch-2.9.1%2Bcpu-cp311-cp311-manylinux_2_28_x86_64.whl
      - rouge-score
      - bert-score
      - openai
