[project]
name = "aula05"
version = "0.1.0"
requires-python = ">=3.12"
dependencies = [
    "en-core-web-sm",
    "ipykernel>=7.3.0",
    "matplotlib>=3.11.1",
    "pandas>=3.0.5",
    "scikit-learn>=1.9.0",
    "spacy>=3.8.16",
    "vadersentiment>=3.3.2",
]

[tool.uv.sources]
en-core-web-sm = { url = "https://github.com/explosion/spacy-models/releases/download/en_core_web_sm-3.8.0/en_core_web_sm-3.8.0-py3-none-any.whl" }
